"""
LangGraph Planner Node using Groq SDK.

This node takes the user's main objective and generates a structured plan
of steps using the Llama-3.1-70b-versatile model on Groq.
"""

import os
from typing import List
from groq import AsyncGroq
from pydantic import BaseModel, Field

# Initialize Groq client (API key loaded from env)
groq_client = AsyncGroq(api_key=os.getenv("GROQ_API_KEY"))


class PlanStep(BaseModel):
    """A single step in the execution plan."""
    step_number: int = Field(description="The order of the step (1-indexed)")
    description: str = Field(description="Clear instruction for this step")


class PlanResponse(BaseModel):
    """The complete plan generated by the planner."""
    objective: str = Field(description="The confirmed objective being solved")
    steps: List[PlanStep] = Field(description="Ordered list of steps to achieve the objective")


async def planner_node(state: dict) -> dict:
    """
    LangGraph node that generates a high-level plan for the browser agent.
    
    Args:
        state: The current graph state containing 'objective'.
        
    Returns:
        Updated state with 'plan' and 'step_index' initialized.
    """
    objective = state.get("objective")
    
    if not objective:
        raise ValueError("No objective found in state")

    system_prompt = """You are an expert web automation planner. 
Your task is to break down a user's high-level objective into a logical sequence of concrete steps.
Each step should be a single action (e.g., "Navigate to URL", "Click login button", "Type username").
Do NOT include reasoning or extra text. Output ONLY valid JSON matching the schema.
Ensure the steps are sequential and cover the entire workflow."""

    user_prompt = f"Objective: {objective}"

    try:
        completion = await groq_client.chat.completions.create(
            model="llama-3.1-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.2,
            max_tokens=1024
        )

        content = completion.choices[0].message.content
        if not content:
            raise ValueError("Empty response from Groq")

        # Parse and validate using Pydantic
        plan_data = PlanResponse.model_validate_json(content)
        
        # Convert PlanStep objects to dictionaries for serialization if needed, 
        # but keeping them as dicts in the state is usually safer for LangGraph
        steps_list = [step.model_dump() for step in plan_data.steps]

        return {
            "plan": steps_list,
            "step_index": 0,
            "confirmed_objective": plan_data.objective
        }

    except Exception as e:
        print(f"Planner node error: {e}")
        # Return error signal in state
        return {
            "error": f"Planning failed: {str(e)}",
            "plan": [],
            "step_index": 0
        }
